version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nodeapp
    networks:
      - app-network

  nodeapp:
    build: ./nodeapp
    volumes:
      - ./nodeapp:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=nodedb
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data-nodeapp:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

volumes:
  mysql-data-nodeapp:

networks:
  app-network: